### ISSUE TITLE
第一章优化建议

### ISSUE THREAD

**Issue by Bmorning** [yangbo5207/reactzhiming#4]
![image](https://user-images.githubusercontent.com/30224480/116641816-12c9ab00-a9a0-11eb-835f-fffc6ef50fef.png)

“该文章”改为“本文”更合适一点

**Comment by Bmorning** [comment]
![image](https://user-images.githubusercontent.com/30224480/116642486-9768f900-a9a1-11eb-89d3-70b848de96a5.png)

改为“什么样的选择更适合当前的技术团队”或者“如何做出最适合当前技术团队的选择”更通畅一点

**Comment by yangbo5207** [comment]
好的，已修改
