### ISSUE TITLE
第二章-文字建议、语法建议

### ISSUE THREAD

**Issue by Makus577** [yangbo5207/reactzhiming#6]
1. 第二段中“React 帮助我完成了非常多的项目，web 端的，app 的，桌面端的。简单的有一个普通页面的展示，复杂的有一个独立的大型股票交易系统” 改成：“Web 端的，App端的，桌面端的。简单到一个普通页面的展示，复杂到一个独立的大型股票交易系统”；

2. 第三段中”熟练的掌握 React 让我轻松得到了许多好的工作机会“ 改成：“熟练地..........“；
3. 文章中的”React hooks“ 应该是 ”React Hooks“；
4. 文章中的”web 网页“ 应该是 ”Web 网页“；
5. 正确看待 React 的学习难度 中的序号1，2，3，4，5中。前面应该是分号，最后一段是句号。
6. 文章结束的 ”扎实的 html/css 基础 “ 应该是 ”扎实的HTML/CSS基础“； 
7. 文章中的”而针对这些学习中的痛点，本书都会一一解决。让 React 的学习变得更加轻松“，这里也没有比较级，不应该用“更加”；
8. 文章中的“他在项目构建的过程中扮演了什么角色” 改成“它。。。。。。”；
9. 文章中的“那么和其他前端框架相比，为什么 React 更难学一点呢？” 改成 “那么和其它。。。。”。

**Comment by yangbo5207** [comment]
给力，已修改
