### ISSUE TITLE
第三章-优化建议及错别字

### ISSUE THREAD

**Issue by Kevin7C** [yangbo5207/reactzhiming#7]
**本书第三章**

**建议描述**
1.原文出处：我们能够利用这种思维，将一个项目的大问题，一层层拆分为只需要实现一个小组件的小问题。
  修改意见：“...,一层层拆分为只需要实现一个**个**小组件的小问题”

2.原文出处：可惜的是，我们并没有任何一种方式，能够如此轻松的得到一个自定义样式的组件。
   修改意见：如此轻松**地**.....

3.原文出处：可能包括一些音效资源
    修改意见：音**频**资源

4.原文出处：我们必须分别处理 html 标签，js 逻辑，css 样式。漏掉一个，就无法呈现完整的按钮。
   修改意见：css 样式**，**漏掉一个

5.原文出处：在代码实现中，组件化主要体现在聚合上，我们会先编写一个个单独的组件，然后在更大的组件中聚合在一起。
   修改意见：然后在更大的组件中**将它们**聚合在一起。

**Comment by yangbo5207** [comment]
好的，已修改
