### ISSUE TITLE
第三章-错别字

### ISSUE THREAD

**Issue by yingwinwin** [yangbo5207/reactzhiming#8]
**本书第三章**
![image](https://user-images.githubusercontent.com/55273635/116801887-ac2fc300-ab40-11eb-90ee-e786f164bc07.png)

**建议描述**
这个是不是说“一成不变”

**Comment by yingwinwin** [comment]
![image](https://user-images.githubusercontent.com/55273635/116801971-8951de80-ab41-11eb-961e-1c3cc3429f2f.png)
这里图片一直加载不出来，一开始我以为是我的网的问题，但是下面的图我是可以加载出来的。。不知道是什么原因，是不是路径写错了？

**Comment by yingwinwin** [comment]
![image](https://user-images.githubusercontent.com/55273635/116802021-08dfad80-ab42-11eb-8ab7-000ace0b846c.png)
我觉得这里好像少了一个“是”，开关就是控制电流的接口

**Comment by yingwinwin** [comment]
![image](https://user-images.githubusercontent.com/55273635/116802048-480dfe80-ab42-11eb-9c36-d97d298d17cd.png)

这里我觉得写成“与 loading 的变化息息相关”，这样读起来好一些，少了个变化，感觉好像少了点啥。

**Comment by yangbo5207** [comment]
给力，已经调整
